
export const SERVICES = [
  {
    id: 'mutual-fund-sip',
    title: 'Mutual Fund & SIP Advisory',
    description: 'Transform your financial aspirations into reality with personalized mutual fund and SIP solutions designed for consistent growth, disciplined investing, and long-term wealth creation.',
    href: '/services#mutual-fund-sip',
    icon: 'Coins',
    focusPoints: ['Strategic Fund Selection', 'Goal-Based SIP Planning', 'Performance Monitoring', 'Portfolio Optimization'],
  },
  {
    id: 'tax-planning',
    title: 'Tax Planning & Advisory',
    description: 'Make smarter tax decisions with personalized planning, compliance-focused solutions, and expert guidance designed to optimize your savings and support your financial goals.',
    href: '/services#tax-planning',
    icon: 'Percent',
    focusPoints: ['Strategic Tax Planning', 'GST Compliance Support', 'Income Tax Assistance', 'Regulatory & Advisory Support'],
  },
  {
    id: 'retirement-planning',
    title: 'Retirement Planning',
    description: 'Prepare for a worry-free retirement with smart financial planning focused on long-term security, wealth preservation, and financial freedom.',
    href: '/services#retirement-planning',
    icon: 'HeartHandshake',
    focusPoints: ['Pension & Income Planning', 'Retirement Corpus Building', 'Inflation Protection Strategies', 'Legacy Planning Solutions'],
  },
  {
    id: 'insurance-solutions',
    title: 'Insurance Solutions',
    description: 'Protect what matters most with comprehensive insurance solutions designed to safeguard your family\'s future, health, and financial well-being.',
    href: '/services#insurance-solutions',
    icon: 'Umbrella',
    focusPoints: ['Life Insurance Planning', 'Health Protection Solutions', 'Asset & Risk Coverage', 'Claims Assistance & Support'],
  },
  {
    id: 'wealth-management',
    title: 'Wealth Management',
    description: 'Create a lasting financial legacy through strategic wealth planning, asset protection, and personalized solutions tailored to your family\'s long-term goals.',
    href: '/services#wealth-management',
    icon: 'TrendingUp',
    focusPoints: ['Estate & Legacy Planning', 'Wealth Protection Strategies', 'Family-Centric Financial Planning', 'Succession & Continuity Planning'],
  },
  {
    id: 'business-finance',
    title: 'Business Finance',
    description: 'Optimize your business finances with expert guidance on cash flow, funding, restructuring, and growth capital strategies.',
    href: '/services#business-finance',
    icon: 'Briefcase',
    focusPoints: ['Cash Flow Management', 'Growth & Expansion Funding', 'Financial Planning Support', 'Risk Assessment & Guidance'],
  },
  {
    id: 'financial-planning',
    title: 'Financial Planning',
    description: 'Take control of your financial future with tailored strategies that align your investments, savings, and financial decisions with your life goals.',
    href: '/services#financial-planning',
    icon: 'LineChart',
    focusPoints: ['Goal-Based Planning', 'Budget Management', 'Investment Strategy', 'Risk Assessment'],
  },
  {
    id: 'nri-investment',
    title: 'NRI Investment Services',
    description: 'Manage your investments in India with confidence through personalized financial solutions designed to help NRIs grow, protect, and optimize their wealth seamlessly.',
    href: '/services#nri-investment',
    icon: 'Globe',
    focusPoints: ['NRI Portfolio Management', 'Repatriation Assistance', 'Tax Compliance Support', 'Cross-Border Financial Planning'],
  },
  {
    id: 'portfolio-review',
    title: 'Portfolio Review & Rebalancing',
    description: 'Keep your investments aligned with your financial goals through regular portfolio reviews and strategic adjustments designed to enhance performance and manage risk effectively.',
    href: '/services#portfolio-review',
    icon: 'RefreshCw',
    focusPoints: ['Portfolio Performance Review', 'Asset Allocation Analysis', 'Risk Assessment & Optimization', 'Strategic Portfolio Rebalancing'],
  },
  {
    id: 'estate-planning',
    title: 'Estate Planning',
    description: 'Secure your family\'s future with thoughtful estate planning solutions designed to protect your assets and ensure a smooth transfer of wealth across generations.',
    href: '/services#estate-planning',
    icon: 'FileText',
    focusPoints: ['Will Planning & Documentation', 'Succession Planning', 'Nomination Management', 'Legal Documentation Support'],
  },
];
